### PR TITLE
INTYGFV-16253: Replaced special characters in HTML elements

### PR DESCRIPTION
**Pull request by mhornfeldt**
We couldn't find a better solution than this. If anyone has a better idea we are open for discussion!

Co-authored-by: Mikaela Romild <mikaela.romild@soprasteria.com>

### CODE REVIEW

**Comment by ChrilleSigerhed** [comment]
Its great that we could find a way to fix the issue and the end of the "transformation" of the certificate elements. But I think it adds a layer of unnesserary complexity to the formatting to HTML.

A suggestion to consider moving forward:
Move the htmlEscape logic to the converter layer. 
If we introduce a TextSanitizerUtil-class, with good test coverage, all we need to do is simply implement it where its needed.

I think it might be worth it. What do you think?

**Comment by mhornfeldt** [comment]
> Its great that we could find a way to fix the issue and the end of the "transformation" of the certificate elements. But I think it adds a layer of unnesserary complexity to the formatting to HTML.
> 
> A suggestion to consider moving forward: Move the htmlEscape logic to the converter layer. If we introduce a TextSanitizerUtil-class, with good test coverage, all we need to do is simply implement it where its needed.
> 
> I think it might be worth it. What do you think?

We discussed having the logic further up. However, it will be easy for text values, but the other questions are more complex in terms of where the values are placed. I'm not sure what you mean with the converter layer, but if you mean that the htmlEscape should be performed in "FormattedQuestionConverter". I see problems related to that the question objects should be held immutable. Today we send value-objects down to the HTMLFactories so we won't have the pure text values before that. I'm also unsure of what complexity you mean regarding the HTML?

**Comment by mhornfeldt** [comment]
Added function as discussed :)

**Review by ChrilleSigerhed — APPROVED** [review]
Well done, I think this was a great improvement.

**Pull request merged**
